# Generated by Django 5.1.3 on 2024-12-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0002_brands_category_country_advertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='advertise',
            name='cars_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars_app.cars_type'),
        ),
    ]
