# Generated by Django 5.1.3 on 2024-12-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0005_rename_author_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
