# Generated by Django 5.1.3 on 2024-12-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0006_delete_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='name',
            field=models.CharField(default='haha', max_length=255),
            preserve_default=False,
        ),
    ]
